server:
    port: 8084

keycloak:
  auth-server-url: http://localhost:9090/auth
  realm: Keycloak-EmployeeService
  resource: demo
  public-client: true
  bearer-only: true

#  keycloak:
#    auth-server-url: http://localhost:8080/auth
#    realm: Employee_CRUD
#    resource: demo
#    public-client: true
#    bearer-only: true




